#!/usr/bin/env bash

destination=~/Desktop
format=wav

if [[ -f ~/.wavtaprc ]]; then
	destination=`cat ~/.wavtaprc | perl -ni -e 'm/destination:\s*([^\n]+)/ && print "$1\n";' | tail -1`
	format=`cat ~/.wavtaprc | perl -ni -e 'm/format:\s*([^\n]+)/ && print "$1\n";' | tail -1`
fi

recorder_process='/Applications/WavTap.app/Contents/SharedSupport/sox'
pid=`ps -axo pid,command,args | grep $recorder_process | grep -v grep | awk '{ print $1 }'`

if [[ -n $pid ]]; then
  kill -SIGINT $pid
else
	/Applications/WavTap.app/Contents/SharedSupport/sox -V6 -t coreaudio 'WavTap (2ch)' $destination/`date +%s`.$format
fi
