#!/usr/bin/env bash

if [[ -n "$2" ]]; then
	format=$2
elif [[ -f ~/.wavtaprc ]]; then
	format=`cat ~/.wavtaprc | perl -ni -e 'm/format:\s*([^\n]+)/ && print "$1\n";' | tail -1`
else
	format=wav
fi

if [[ -d "$1" ]]; then
	output_file=`echo $1 | sed 's|/$||g'`$format
elif [[ -f "$1" ]]; then
	output_file=$1
elif [[ -n "$1" ]]; then
	touch "$1" && output_file=$1
elif [[ -f ~/.wavtaprc ]]; then
	output_file=`cat ~/.wavtaprc | perl -ni -e 'm/destination:\s*([^\n]+)/ && print "$1\n";' | tail -1`
else
	output_file=~/Desktop/`date +%s`.$format
fi

recorder_process='/Applications/WavTap.app/Contents/SharedSupport/sox'
pid=`ps -axo pid,command,args | grep $recorder_process | grep -v grep | awk '{ print $1 }'`

if [[ -n $pid ]]; then
  kill -SIGINT $pid
else
	/Applications/WavTap.app/Contents/SharedSupport/sox -V6 -t coreaudio 'WavTap (2ch)' $output_file
fi
