#!/bin/sh
# 
# Apple's installer seems to apply the owner and group for files properly, but not folders
# The folders need to be applied too or our kext will not load

echo "fixing ownership for the Soundflower Kernel Extension"

sudo chown -R root /System/Library/Extensions/Soundflower.kext
sudo chgrp -R wheel /System/Library/Extensions/Soundflower.kext

# Administrators who are not user 501 need to be able to remove (etc.) the stuff installed for Soundflower

echo "fixing accessibility of installed files for all admin users"

sudo chmod -R a+r /Applications/Soundflower
sudo chmod -R g+w /Applications/Soundflower
sudo chmod a+x /Applications/Soundflower
